from django.contrib import admin
from kiosco.models import *

admin.site.register(Proveedor)
admin.site.register(Cliente)
admin.site.register(Categoria)
admin.site.register(NombreProducto)
admin.site.register(Etiqueta)
admin.site.register(Marca)
admin.site.register(TipoMedida)
admin.site.register(Medida)
admin.site.register(Moneda)
admin.site.register(Producto)
admin.site.register(Caja)
admin.site.register(ItemFactura)
admin.site.register(Factura)
admin.site.register(Impuesto)
admin.site.register(Descuento)
admin.site.register(ListaDePrecio)
admin.site.register(Carrito)
admin.site.register(MedioDePago)
admin.site.register(Pedido)
admin.site.register(VentaFisica)
admin.site.register(PagoFisico)
admin.site.register(Tarifa)
admin.site.register(Servicio)
admin.site.register(ImpuestoAPagar)
admin.site.register(Empleado)
admin.site.register(CostoFijo)
